"""Tracker-isolation guard for Alembic migrations (R1 mitigation).

LAYERED defense. Each layer can fail without compromising the others.

  1. RUNTIME DDL inspection (`runtime_ddl_check`) — fires on every cursor
     execute via SQLAlchemy `before_cursor_execute`. Refuses any DDL that
     references a forbidden schema, regardless of how the migration was
     authored. Catches hand-written migrations, autogenerated migrations,
     and ops we forgot to handle. **Primary defense.**

  2. SEARCH-PATH lockdown (`SEARCH_PATH_SQL`) — set on the migration
     connection at `run_migrations_online` startup. PostgreSQL's
     default-schema fallback can no longer leak unqualified DDL into
     `public`; every unqualified `CREATE TABLE foo (...)` lands in
     `tooling`.

  3. AUTOGENERATE-time op walker (`process_revision_directives`,
     `include_object`) — early warning during `alembic revision
     --autogenerate`. Validates every schema-bearing field on every
     emitted op. Refuses `ExecuteSQLOp` outright. Recurses into nested
     op containers (`ModifyTableOps` etc.).

The ULTIMATE belt is the production database GRANT policy: the
`lance_tooling` DB user must have DDL privileges only on `tooling` and
`shared`. See `docs/07-risks.md` R1 for the GRANT template. Code-level
guards stop honest mistakes; DB GRANTs stop adversaries.

# Why None schemas are forbidden

`op.create_table('foo')` without an explicit schema is created in the
connection's `search_path` default. Even with layer 2 in place, the
intent should be unambiguous in the generated revision file. Layer 3
refuses any op whose schema field is `None` so reviewers don't have
to reason about the runtime path resolution.

# Why ExecuteSQLOp is refused outright

Raw SQL via `op.execute(...)` defeats schema introspection — we'd have
to parse SQL to validate it, which is fragile. If a real need arises,
design an opt-in mechanism (e.g., a per-revision `ALLOW_RAW_SQL =
"reason"` constant) rather than leaving the hatch open by default.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterator
from typing import Any

_logger = logging.getLogger("alembic.guard")

ALLOWED_SCHEMAS: frozenset[str] = frozenset({"tooling", "shared"})
FORBIDDEN_SCHEMAS: frozenset[str] = frozenset({"tracker"})

# Op types with no schema-bearing field that are nonetheless safe. Empty
# by design — every Phase 1 / Phase 2 op we use names a schema. If you
# need to add an entry, document the reason inline.
_SCHEMA_FREE_OPS: frozenset[str] = frozenset()

# Op types refused outright. Raw SQL defeats introspection.
_FORBIDDEN_OP_TYPES: frozenset[str] = frozenset({"ExecuteSQLOp"})


# ============================================================================
# Layer 3: autogenerate-time op-walker
# ============================================================================


def _check_schema_value(schema: str | None, source: str) -> None:
    """Validate a single schema string. None is forbidden (Bug 2 fix)."""
    if schema is None:
        raise RuntimeError(
            f"Refusing migration: {source} is None. PostgreSQL would route "
            "this to the connection's search_path default; tooling migrations "
            "must set the schema to 'tooling' or 'shared' explicitly. See "
            "migrations/_guard.py."
        )
    if schema in FORBIDDEN_SCHEMAS:
        raise RuntimeError(
            f"Refusing migration: {source} targets forbidden schema "
            f"'{schema}'. Tooling migrations may only touch "
            f"{sorted(ALLOWED_SCHEMAS)}. See docs/07-risks.md R1."
        )
    if schema not in ALLOWED_SCHEMAS:
        raise RuntimeError(
            f"Refusing migration: {source} targets unknown schema "
            f"'{schema}'. Allowed: {sorted(ALLOWED_SCHEMAS)}."
        )


def _collect_schema_values(op: Any) -> dict[str, str | None]:
    """Walk every schema-bearing field on an Alembic op (Bug 1 fix).

    Looks in two places:
      (a) Public attributes whose name ends in 'schema' — covers
          CreateTableOp.schema, AlterColumnOp.schema, etc.
      (b) Keys ending in 'schema' inside `op.kw` dict — covers
          CreateForeignKeyOp.kw['source_schema'] / kw['referent_schema'],
          which alembic stashes there instead of as direct attributes.
    """
    out: dict[str, str | None] = {}
    for attr in dir(op):
        if attr.startswith("_") or not attr.endswith("schema"):
            continue
        try:
            value = getattr(op, attr)
        except Exception:
            continue
        if value is None or isinstance(value, str):
            out[attr] = value
    kw = getattr(op, "kw", None)
    if isinstance(kw, dict):
        for key, value in kw.items():
            if not isinstance(key, str) or not key.endswith("schema"):
                continue
            if value is None or isinstance(value, str):
                out[f"kw[{key!r}]"] = value
    return out


def check_op_schemas(op: Any) -> None:
    """Validate every schema-bearing field on `op`. Raises on violation."""
    op_type = type(op).__name__
    if op_type in _FORBIDDEN_OP_TYPES:
        raise RuntimeError(
            f"Refusing migration: {op_type} is not allowed. Raw SQL or "
            "schema-opaque ops defeat tracker-isolation introspection. "
            "If you have a deliberate need, design an opt-in mechanism "
            "in migrations/_guard.py first."
        )
    schemas = _collect_schema_values(op)
    if not schemas:
        if op_type not in _SCHEMA_FREE_OPS:
            raise RuntimeError(
                f"Refusing migration: op {op_type} has no schema-bearing "
                "field and is not in the schema-free allowlist. Tooling "
                "migrations must be schema-explicit."
            )
        return
    for source, value in schemas.items():
        _check_schema_value(value, f"op {op_type}.{source}")


def walk_ops(container: Any) -> Iterator[Any]:
    """Yield every op in a directives container, recursing into nested
    containers (`ModifyTableOps` etc.)."""
    if container is None:
        return
    for op in getattr(container, "ops", []):
        yield op
        if hasattr(op, "ops"):
            yield from walk_ops(op)


def process_revision_directives(context_, revision, directives) -> None:
    """Alembic hook: validate every op (including nested) in an autogenerated
    revision. Raises on the first forbidden op so the revision file is never
    written."""
    for directive in directives:
        for ops_container in (
            getattr(directive, "upgrade_ops", None),
            getattr(directive, "downgrade_ops", None),
        ):
            for op in walk_ops(ops_container):
                check_op_schemas(op)


def include_object(
    obj: Any,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: Any,
) -> bool:
    """Alembic hook: filter reflected DB objects during autogenerate.

    For tables/columns/indexes: uses `obj.schema`. For foreign-key constraints:
    additionally checks the referent table's schema, so an FK whose source is
    in an allowed schema but whose target is `tracker.*` is excluded.
    """
    if type_ == "foreign_key_constraint":
        src = getattr(getattr(obj, "table", None), "schema", None)
        ref = getattr(getattr(obj, "referred_table", None), "schema", None)
        for label, schema in (("source", src), ("referent", ref)):
            if schema is not None and schema in FORBIDDEN_SCHEMAS:
                _logger.warning(
                    "excluding FK '%s' with %s schema in forbidden '%s'",
                    name,
                    label,
                    schema,
                )
                return False
        return True
    schema = getattr(obj, "schema", None)
    if schema is None:
        return True  # legitimately schema-free reflected objects (e.g. some indexes)
    if schema in FORBIDDEN_SCHEMAS:
        _logger.warning("excluding %s '%s' in forbidden schema '%s'", type_, name, schema)
        return False
    return schema in ALLOWED_SCHEMAS


# ============================================================================
# Layer 1: runtime DDL inspection
# ============================================================================

_DDL_KEYWORD_RE = re.compile(
    r"\b(CREATE|ALTER|DROP|TRUNCATE|GRANT|REVOKE|COMMENT|RENAME)\b",
    re.IGNORECASE,
)

# Match `<schema>.<identifier>` with optional double quotes. Boundary on the
# left ensures we don't pick up things like `foo.bar.baz` middle parts.
_QUALIFIED_REF_RE = re.compile(
    r"""
    (?:^|[\s\(,;=])           # boundary: start, whitespace, paren, comma, semi, equals
    "?([a-z_][a-z0-9_]*)"?    # captured: schema name (optionally quoted)
    \s*\.\s*                  # dot
    "?[a-z_]                  # start of object identifier
    """,
    re.IGNORECASE | re.VERBOSE,
)


def _statement_is_ddl(statement: str) -> bool:
    return bool(_DDL_KEYWORD_RE.search(statement))


def runtime_ddl_check(statement: str) -> None:
    """Refuse DDL statements that reference a forbidden schema.

    Pure function — testable directly with synthetic SQL strings. Wired
    into SQLAlchemy via `runtime_ddl_event` below.
    """
    if not _statement_is_ddl(statement):
        return
    seen: set[str] = set()
    for match in _QUALIFIED_REF_RE.finditer(statement):
        schema = match.group(1).lower()
        if schema in seen:
            continue
        seen.add(schema)
        if schema in FORBIDDEN_SCHEMAS:
            preview = " ".join(statement.split())[:200]
            raise RuntimeError(
                f"Refusing DDL: forbidden schema '{schema}' referenced. "
                "See docs/07-risks.md R1.\n"
                f"Statement: {preview}"
            )


def runtime_ddl_event(
    conn: Any,
    cursor: Any,
    statement: str,
    parameters: Any,
    context: Any,
    executemany: bool,
) -> None:
    """SQLAlchemy `before_cursor_execute` listener — wraps `runtime_ddl_check`."""
    runtime_ddl_check(statement)


# ============================================================================
# Layer 2: search-path lockdown SQL
# ============================================================================

# `SET search_path` ensures unqualified DDL routes to `tooling` (the first
# entry), never to `public`. Applied once per connection in env.py.
SEARCH_PATH_SQL: str = "SET search_path TO " + ", ".join(sorted(ALLOWED_SCHEMAS))


__all__ = [
    "ALLOWED_SCHEMAS",
    "FORBIDDEN_SCHEMAS",
    "SEARCH_PATH_SQL",
    "check_op_schemas",
    "include_object",
    "process_revision_directives",
    "runtime_ddl_check",
    "runtime_ddl_event",
    "walk_ops",
]
