"""Alembic environment for lance-tooling.

Wires the tracker-isolation guard into Alembic's hooks. All policy logic
lives in `migrations/_guard.py` so it's unit-testable without bringing up
Alembic. See that module's docstring for the layered-defense explanation.
"""

from __future__ import annotations

import logging
import sys

from alembic import context
from sqlalchemy import engine_from_config, event, pool

from migrations._guard import (
    SEARCH_PATH_SQL,
    include_object,
    process_revision_directives,
    runtime_ddl_event,
)

_logger = logging.getLogger("alembic.env")

config = context.config

# Empty for v1: hand-written migrations only. When models land in Phase 3,
# replace with the model registry's metadata so autogenerate works; the
# schema-isolation filters in `_guard` keep working unchanged.
target_metadata = None


def run_migrations_offline() -> None:
    """`alembic upgrade --sql` path. No DB connection; SQL is rendered to
    stdout. The runtime DDL guard cannot fire here — review the rendered
    SQL before applying it manually."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        process_revision_directives=process_revision_directives,
        include_schemas=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """`alembic upgrade` path against a live DB.

    All three guard layers are active:
      1. Runtime DDL guard: SQLAlchemy event listener on the engine
      2. Search-path lockdown: SET search_path on the connection
      3. Autogenerate guard: include_object + process_revision_directives
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    # Layer 1: refuse DDL referencing forbidden schemas before the cursor
    # ever executes it. Listener stays attached for the engine's lifetime.
    event.listen(connectable, "before_cursor_execute", runtime_ddl_event)

    with connectable.connect() as connection:
        # Layer 2: lock search_path so unqualified DDL routes to `tooling`,
        # never to `public`. exec_driver_sql avoids the SQLAlchemy parser
        # interpreting this as a parameterized statement.
        connection.exec_driver_sql(SEARCH_PATH_SQL)

        # Layer 3: include_object + process_revision_directives validate
        # autogenerated revisions before they're written.
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            process_revision_directives=process_revision_directives,
            include_schemas=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    try:
        run_migrations_online()
    except Exception as exc:  # pragma: no cover
        print(f"alembic env failed: {exc}", file=sys.stderr)
        raise
